print ('Hello!')
print ('World!')
print ('Editing from another pc')
print('add more stuff from another pc')
print ('Hello!')
print ('World!')
print ('Editing from another pc')
print('add more stuff from another pc')